[book]
title = "Atlas77"
authors = ["Gipson62"]
language = "en"
src = "./src"

[build]
build-dir = "../../../docs/docs/latest"

[output.html]
git-repository-url = "https://github.com/atlas77-lang/Atlas77"
site-url = "/docs/latest/"
edit-url-template = "https://github.com/atlas77-lang/Atlas77/edit/main/src/docs/latest/{path}"